main:
  - name: WORLD PIECE
    url: 'https://the.wp.computer'
    weight: 3
  - name: UNIVERSAL PEACE
    url: 'https://apx.up.computer'
    weight: 1
  - name: UNIVERSAL PEACE COMPUTER
    url: 'https://the.up.computer'
    weight: 2
  - name: more
    url: /posts/
    weight: 4
